import type { Metadata } from "next";
import "@/styles/global.css";  
import Navigation from "@/components/ui/Navigation";
import SiteFooter from "@/components/ui/SiteFooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Navigation />
        {children}
        <SiteFooter />
      </body>
    </html>
  );
}
